### PR TITLE
Fix frozen strings could not be scrubbed

### PR DESCRIPTION
**Pull request by waniji**
The scrubbed string was not used in filter_string_scrub.

### CODE REVIEW

**Comment by waniji** [comment]
Resolved conflict.

**Comment by kataring** [comment]
@waniji thanks.

**Comment by waniji** [comment]
@kataring Thank you for merging!
When will the next version be released?

**Comment by kataring** [comment]
>When will the next version be released?

I'll do it this weekend.

**Comment by waniji** [comment]
Thank you so much.

**Pull request merged**
